# Schemas Pydantic para o sistema de pizzaria

# Importações de schemas de autenticação
from .auth_schemas import (
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    RefreshTokenRequest,
    RefreshTokenResponse,
    Token,
    TokenData,
    UserBase,
    UserCreate,
    UserLogin,
    UserResponse,
    UserUpdate,
)

# Importações de schemas comuns
from .common_schemas import (
    BulkOperationRequest,
    BulkOperationResponse,
    ErrorResponse,
    ExportRequest,
    ExportResponse,
    FileUploadResponse,
    HealthCheckResponse,
    MessageResponse,
    NotificationResponse,
    PaginatedResponse,
    PaginationMeta,
    PaginationParams,
    SearchFilters,
    StatisticsResponse,
    SystemConfigResponse,
    ValidationErrorResponse,
)

# Importações de schemas de pedidos
from .order_schemas import (  # Enums; Schemas de itens; Schemas de pedidos; Relatórios
    AddressBase,
    ItemBase,
    ItemCategory,
    ItemCreate,
    ItemResponse,
    ItemSize,
    ItemUpdate,
    OrderBase,
    OrderCreate,
    OrderItemBase,
    OrderItemCreate,
    OrderItemResponse,
    OrderResponse,
    OrderStatus,
    OrderSummary,
    OrderUpdate,
    PaymentMethod,
    SalesReport,
)

__all__ = [
    # Auth schemas
    'UserBase',
    'UserCreate',
    'UserUpdate',
    'UserResponse',
    'UserLogin',
    'TokenData',
    'Token',
    'RefreshTokenRequest',
    'RefreshTokenResponse',
    'PasswordChange',
    'PasswordReset',
    'PasswordResetConfirm',
    # Order schemas
    'ItemCategory',
    'ItemSize',
    'OrderStatus',
    'PaymentMethod',
    'ItemBase',
    'ItemCreate',
    'ItemUpdate',
    'ItemResponse',
    'OrderItemBase',
    'OrderItemCreate',
    'OrderItemResponse',
    'AddressBase',
    'OrderBase',
    'OrderCreate',
    'OrderUpdate',
    'OrderResponse',
    'OrderSummary',
    'SalesReport',
    # Common schemas
    'MessageResponse',
    'ErrorResponse',
    'ValidationErrorResponse',
    'PaginationMeta',
    'PaginatedResponse',
    'HealthCheckResponse',
    'SearchFilters',
    'PaginationParams',
    'BulkOperationRequest',
    'BulkOperationResponse',
    'StatisticsResponse',
    'FileUploadResponse',
    'ExportRequest',
    'ExportResponse',
    'SystemConfigResponse',
    'NotificationResponse',
]
